@testable import WingDex
import Compression
import XCTest

enum ParityFixtureError: Error {
    /// The blob named by `shippedPriorName` is not in public/priors. Regenerating
    /// the prior changes its content-hash name, so this fires when the app, the
    /// iOS sync script and this test have drifted apart.
    case missingShippedPrior(String)
    case gunzipFailed(String)
}

/// Parity between the Swift bird-ID math and the TypeScript it was ported from.
///
/// The vectors come from src/__tests__/birdid-golden.test.ts, which pins the
/// web output to Fixtures/birdid-golden.json. Two implementations of the same
/// math drift, and the failure mode is silent: a mis-keyed cell or a shifted
/// month still returns a plausible ranked list. Regenerate both sides with
/// `UPDATE_GOLDEN=1 npx vitest run birdid-golden` from the repo root.
final class BirdIDParityTests: XCTestCase {
    // MARK: Golden fixture

    private struct Golden: Decodable {
        struct Cell: Decodable { let row: Int; let col: Int }
        struct Point: Decodable {
            let name: String
            let lat: Double
            let lon: Double
            let x: Double
            let y: Double
            let cell: Cell?
        }
        struct CellPrior: Decodable {
            let name: String
            let row: Int
            let col: Int
            let month: Int
            let count: Int?
            let sample: [[Double]]?
        }
        struct BadMonth: Decodable { let month: Int; let count: Int? }
        struct Candidate: Decodable { let idx: Int; let sim: Double }
        struct ScoredRow: Decodable {
            let idx: Int
            let sim: Double
            let score: Double
            let logP: Double?
        }
        struct RankCase: Decodable {
            let name: String
            let lat: Double?
            let lon: Double?
            let month: Int?
            let scored: [ScoredRow]
            let probs: [Double]
        }
        struct Probe: Decodable {
            let bias: Double
            let plattA: Double
            let plattB: Double
            let threshold: Double
        }
        struct Calibration: Decodable {
            let temperature: Double
            let beta: Double
            let probe: Probe
        }

        let taxonomySha16: String
        let calibration: Calibration
        let blobVersion: Int
        let blobTaxHash: String
        let candidates: [Candidate]
        let projection: [Point]
        let cellPriors: [CellPrior]
        let badMonths: [BadMonth]
        let ranking: [RankCase]
    }

    /// The golden JSON lives beside this source file. It is small and tracked.
    private static let fixtureDir = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .appendingPathComponent("Fixtures")

    private static let repoRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()  // WingDexTests
        .deletingLastPathComponent()  // ios
        .deletingLastPathComponent()  // repo root

    private static func loadGolden() throws -> Golden {
        let url = fixtureDir.appendingPathComponent("birdid-golden.json")
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(Golden.self, from: data)
    }

    /// The exact prior the app ships, read from the tracked web artifact.
    ///
    /// This used to read a gitignored 23 MiB copy under Fixtures/, generated by
    /// hand, so all six tests here skipped on every CI run and the parity they
    /// assert was never checked. public/priors/occurrence.*.bin.gz IS tracked, and
    /// ios/scripts/sync-birdid-assets.sh already gunzips that exact file into the
    /// app bundle. Reading it directly needs no new bytes in the repo and tests the
    /// artifact that actually ships.
    ///
    /// It also used to require that public/priors held EXACTLY ONE blob, so that a
    /// stale leftover could not be picked up silently. public/priors now holds two
    /// on purpose: the shipped v4, and the v3 that the web suite reads to prove the
    /// v4 reader still parses blobs still cached in the wild. Naming the shipped
    /// file keeps that guard rather than dropping it: an unrelated extra blob is
    /// ignored, and a missing shipped blob fails loudly instead of silently
    /// substituting whichever name happened to sort first. The name must stay in
    /// step with MODEL_ASSET_URLS in src/lib/bird-id-local-adapter.ts and with the
    /// input path of the Sync Bird ID Assets build phase.
    static let shippedPriorName = "occurrence.4f5c1a15.bin.gz"

    /// The decompressed prior, inflated once. It is 23 MiB, and five tests read it.
    private static let cachedPriorBytes: Result<[UInt8], Error> = {
        do {
            let gz = repoRoot
                .appendingPathComponent("public/priors")
                .appendingPathComponent(shippedPriorName)
            guard FileManager.default.fileExists(atPath: gz.path) else {
                return .failure(ParityFixtureError.missingShippedPrior(gz.path))
            }
            return .success(try gunzip(Data(contentsOf: gz)))
        } catch {
            return .failure(error)
        }
    }()

    static func priorBytes() throws -> [UInt8] {
        try cachedPriorBytes.get()
    }

    private static func loadBlob(_ g: Golden) throws -> OccurrenceBlob {
        try OccurrenceBlob(raw: Self.priorBytes(), taxonomySha16: g.taxonomySha16)
    }

    // MARK: Projection

    func testEqualEarthProjectionMatchesWeb() throws {
        let g = try Self.loadGolden()
        for p in g.projection {
            let got = EqualEarth.project(lon: p.lon, lat: p.lat)
            // Metres. The grid cell is 27 km, so 1e-6 m is far inside the
            // rounding that could change a cell.
            XCTAssertEqual(got.x, p.x, accuracy: 1e-6, "x for \(p.name)")
            XCTAssertEqual(got.y, p.y, accuracy: 1e-6, "y for \(p.name)")
        }
    }

    func testGridCellMatchesWebIncludingOffGrid() throws {
        let g = try Self.loadGolden()
        var offGrid = 0
        for p in g.projection {
            let got = EqualEarth.cell(lat: p.lat, lon: p.lon)
            if let want = p.cell {
                XCTAssertEqual(got?.row, want.row, "row for \(p.name)")
                XCTAssertEqual(got?.col, want.col, "col for \(p.name)")
            } else {
                offGrid += 1
                XCTAssertNil(got, "\(p.name) should fall outside the grid")
            }
        }
        XCTAssertGreaterThan(offGrid, 0, "fixture should cover the off-grid path")
    }

    // MARK: Occurrence blob

    func testBlobHeaderMatchesWeb() throws {
        let g = try Self.loadGolden()
        let occ = try Self.loadBlob(g)
        XCTAssertEqual(occ.version, g.blobVersion)
        XCTAssertEqual(occ.taxonomyHash, g.blobTaxHash)
    }

    func testBlobRejectsWrongTaxonomyHash() throws {
        let g = try Self.loadGolden()
        let raw = try Self.priorBytes()
        XCTAssertThrowsError(try OccurrenceBlob(raw: raw, taxonomySha16: "deadbeefdeadbeef")) {
            guard case OccurrenceBlob.ParseError.taxonomyMismatch = $0 else {
                return XCTFail("expected taxonomyMismatch, got \($0)")
            }
        }
        XCTAssertNoThrow(try OccurrenceBlob(raw: raw, taxonomySha16: g.taxonomySha16))
    }

    func testBlobRejectsTruncatedIndex() throws {
        let g = try Self.loadGolden()
        // Truncating AFTER the 16-byte header passes magic, version and hash.
        let raw = [UInt8](try Self.priorBytes().prefix(64))
        XCTAssertThrowsError(try OccurrenceBlob(raw: raw, taxonomySha16: g.taxonomySha16)) {
            guard case OccurrenceBlob.ParseError.truncatedIndex = $0 else {
                return XCTFail("expected truncatedIndex, got \($0)")
            }
        }
    }

    func testCellPriorsMatchWeb() throws {
        let g = try Self.loadGolden()
        let occ = try Self.loadBlob(g)
        for c in g.cellPriors {
            let got = occ.cellPriors(row: c.row, col: c.col, month: c.month)
            guard let count = c.count else {
                XCTAssertNil(got, "\(c.name) month \(c.month) should have no data")
                continue
            }
            XCTAssertEqual(got?.count, count, "species count for \(c.name) month \(c.month)")
            for pair in c.sample ?? [] {
                let idx = Int(pair[0])
                XCTAssertEqual(got?[idx] ?? .nan, pair[1], accuracy: 1e-12,
                               "logP for species \(idx) in \(c.name) month \(c.month)")
            }
        }
    }

    /// The old server API took month 0-11 and iOS sent `component(.month) - 1`.
    /// The v3 blob takes 1-12, so a port that kept the subtraction would send 0
    /// for January and shift every other month back by one, with no error.
    func testRejectsTheOldZeroBasedMonthConvention() throws {
        let g = try Self.loadGolden()
        let occ = try Self.loadBlob(g)
        let ref = g.cellPriors.first { $0.count != nil }!
        for bad in g.badMonths {
            XCTAssertNil(occ.cellPriors(row: ref.row, col: ref.col, month: bad.month),
                         "month \(bad.month) must not resolve")
        }
        XCTAssertNil(occ.cellPriors(row: ref.row, col: ref.col, month: nil),
                     "a v3 blob needs a month")
    }

    // MARK: Ranking

    func testRankingMatchesWeb() throws {
        let g = try Self.loadGolden()
        let occ = try Self.loadBlob(g)
        // The probe is carried through from the golden, but rank() never reads
        // it: the ranking below must be identical with or without it, which is
        // the point of applying P_cal outside the species softmax.
        let cal = BirdRanker.Calibration(
            temperature: g.calibration.temperature,
            beta: g.calibration.beta,
            probe: BirdRanker.BirdProbe(bias: g.calibration.probe.bias,
                                        plattA: g.calibration.probe.plattA,
                                        plattB: g.calibration.probe.plattB,
                                        threshold: g.calibration.probe.threshold))
        let cands = g.candidates.map { BirdRanker.Candidate(idx: $0.idx, sim: $0.sim) }

        for c in g.ranking {
            let loc = c.lat.flatMap { lat in c.lon.map { (lat: lat, lon: $0) } }
            let got = BirdRanker.rank(cands, calibration: cal, occurrence: occ,
                                      location: loc, month: c.month)
            XCTAssertEqual(got.map(\.idx), c.scored.map(\.idx), "order for \(c.name)")
            for (i, want) in c.scored.enumerated() {
                XCTAssertEqual(got[i].score, want.score, accuracy: 1e-9,
                               "score \(i) for \(c.name)")
                if let wantLogP = want.logP {
                    XCTAssertEqual(got[i].logP ?? .nan, wantLogP, accuracy: 1e-12,
                                   "logP \(i) for \(c.name)")
                } else {
                    XCTAssertNil(got[i].logP, "logP \(i) for \(c.name) should be nil")
                }
            }
            let probs = BirdRanker.scoresToProbs(got)
            XCTAssertEqual(probs.count, c.probs.count, "prob count for \(c.name)")
            for (i, want) in c.probs.enumerated() {
                XCTAssertEqual(probs[i], want, accuracy: 1e-12, "prob \(i) for \(c.name)")
            }
        }
    }

    func testScoresToProbsIsEmptyForNoCandidates() {
        XCTAssertTrue(BirdRanker.scoresToProbs([]).isEmpty)
    }
}

extension BirdIDParityTests {
    /// Inflate a gzip member using libcompression.
    ///
    /// COMPRESSION_ZLIB decodes a raw DEFLATE stream, so the gzip header has to be
    /// stepped over first and the 8 byte CRC/size trailer dropped. The header is 10
    /// bytes plus whatever optional FEXTRA/FNAME/FCOMMENT/FHCRC fields FLG marks as
    /// present, which is why this cannot just skip a fixed offset.
    static func gunzip(_ data: Data) throws -> [UInt8] {
        // One pass over the original Data. An earlier version went Data -> [UInt8]
        // -> slice -> [UInt8] -> Data and back, copying 23 MiB several times.
        try data.withUnsafeBytes { (buf: UnsafeRawBufferPointer) -> [UInt8] in
            let bytes = buf.bindMemory(to: UInt8.self)
            guard bytes.count > 18, bytes[0] == 0x1f, bytes[1] == 0x8b, bytes[2] == 8 else {
                throw ParityFixtureError.gunzipFailed("not a gzip DEFLATE stream")
            }
            let flg = bytes[3]
            var i = 10
            if flg & 0x04 != 0 {
                guard i + 1 < bytes.count else {
                    throw ParityFixtureError.gunzipFailed("truncated FEXTRA")
                }
                // Parenthesised deliberately: + binds tighter than | in Swift, so
                // `2 + Int(lo) | Int(hi) << 8` reads as `(2 + lo) | (hi << 8)`, a
                // different number whenever lo carries into the high byte.
                let xlen = Int(bytes[i]) | (Int(bytes[i + 1]) << 8)
                i += 2 + xlen
            }
            if flg & 0x08 != 0 {
                while i < bytes.count, bytes[i] != 0 { i += 1 }
                i += 1
            }
            if flg & 0x10 != 0 {
                while i < bytes.count, bytes[i] != 0 { i += 1 }
                i += 1
            }
            if flg & 0x02 != 0 { i += 2 }
            guard i < bytes.count - 8 else {
                throw ParityFixtureError.gunzipFailed("truncated after header")
            }

            // ISIZE, the trailing little-endian uncompressed length, sizes the output
            // exactly. It is attacker-adjacent only in the sense that a corrupt file
            // could ask for gigabytes, so it is capped rather than trusted.
            let n = bytes.count
            let isize = Int(bytes[n - 4]) | (Int(bytes[n - 3]) << 8)
                | (Int(bytes[n - 2]) << 16) | (Int(bytes[n - 1]) << 24)
            let maxISize = 256 << 20
            guard isize > 0, isize <= maxISize else {
                throw ParityFixtureError.gunzipFailed(
                    "ISIZE \(isize) is outside 1...\(maxISize)")
            }

            var out = [UInt8](repeating: 0, count: isize)
            let deflateStart = bytes.baseAddress! + i
            let deflateCount = n - 8 - i
            let written = out.withUnsafeMutableBufferPointer { dst in
                compression_decode_buffer(dst.baseAddress!, isize,
                                          deflateStart, deflateCount,
                                          nil, COMPRESSION_ZLIB)
            }
            guard written == isize else {
                throw ParityFixtureError.gunzipFailed(
                    "inflated \(written) bytes, ISIZE says \(isize)")
            }
            return out
        }
    }
}
