#!/usr/bin/env python3
"""Compute the pBird goldens pinned in ios/WingDexTests/BirdIdEngineTests.swift.

WHY. BirdIdEngine.birdProbability is the only shipped computation with no
behavioural test. The accuracy tests check species ORDER, and the probe is a
positive scalar multiplier applied after ranking, so it cannot change an order.
A swapped Platt pair, a dropped normalisation or a mis-sliced probe row would
therefore leave every existing iOS test green.

A golden fixes that, but it has to come from somewhere other than the Swift it
is testing. This script computes it from the SHIPPED bytes
(public/models/text_classifier_int8.bin, last row) and the SHIPPED constants
(BIRD_PROBE in src/lib/bird-id-local-adapter.ts), using the same arithmetic
src/lib/bird-id-local.ts uses. The Swift then has to reproduce a number it
cannot derive from itself.

The embeddings are generated by a formula the Swift restates literally, so the
test carries no 768-float table.

Run:  python3 ios_probe_golden.py
"""
import os
import re

import numpy as np

import shipped_model as SM

EMBED_DIM = 768
EPS = 1e-7


def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def decode_last_row(path, dim):
    buf = np.fromfile(path, dtype=np.uint8)
    n = len(buf) // (dim + 4)
    assert n * (dim + 4) == len(buf), 'classifier length'
    q = buf[:n * dim].view(np.int8).reshape(n, dim)
    scales = buf[n * dim:].view(np.float32)
    return q[n - 1].astype(np.float64) * float(scales[n - 1]), n


def probe_fields(adapter):
    src = open(adapter).read()
    blk = re.search(r'export const BIRD_PROBE = \{(.*?)\}', src, re.S).group(1)
    def field(name):
        return float(re.search(name + r':\s*([0-9.eE+-]+)', blk).group(1))
    return field('bias'), field('plattA'), field('plattB'), field('threshold')


def p_bird(e, w, bias, pa, pb):
    """Exactly what BirdIdEngine.birdProbability does."""
    norm = float(np.linalg.norm(e)) or 1.0
    raw = float(sigmoid(float(w @ e) / norm + bias))
    c = min(max(raw, EPS), 1.0 - EPS)
    z = float(np.log(c / (1.0 - c)))
    return raw, float(sigmoid(pa * z + pb))


def main():
    clf = os.path.join(SM.REPO_ROOT, 'public', 'models',
                       'text_classifier_int8.bin')
    adapter = os.path.join(SM.REPO_ROOT, 'src', 'lib',
                           'bird-id-local-adapter.ts')
    w, n = decode_last_row(clf, EMBED_DIM)
    bias, pa, pb, thr = probe_fields(adapter)

    print('classifier ' + clf)
    print('  rows ' + str(n) + ', probe is row ' + str(n - 1))
    print('  probe |w| ' + ('%.10f' % float(np.linalg.norm(w))))
    print('  bias ' + repr(bias) + ' plattA ' + repr(pa) +
          ' plattB ' + repr(pb))
    print('  shipped threshold ' + repr(thr))
    print('')

    # Deliberately TWO embeddings, one each side of the shipped gate. A
    # golden on one side only would pass a sign error in the Platt map.
    #
    # The embedding is  e = sin(i+1) for i in 0..767, plus s * w. The sin term
    # is an arbitrary fixed direction with no relation to the probe, and s
    # tilts it toward or away from the probe direction. Stating it as a formula
    # means the Swift test carries no 768-float table, and the two cases differ
    # ONLY in s.
    #
    # s is chosen so neither case saturates. At s = -0.30 or s = +0.20 P_raw is
    # 0 or 1 to Double precision, and a golden there would pass even if plattA
    # were zero. These two land at 0.27 and 0.95, where every constant is
    # load-bearing.
    base = np.sin(np.arange(1, EMBED_DIM + 1, dtype=np.float64))
    cases = [
        ('below the gate', -0.05),
        ('above the gate', -0.02),
    ]
    print('e[i] = sin(i + 1) + s * w[i],  i in 0..767')
    print('')
    for name, s in cases:
        e = base + s * w
        raw, cal = p_bird(e, w, bias, pa, pb)
        side = 'ABOVE' if cal > thr else 'BELOW'
        print(name + '   s = ' + ('%+.2f' % s))
        print('  P_raw ' + ('%.10f' % raw))
        print('  P_cal ' + ('%.10f' % cal) + '   ' + side + ' the threshold')
        if (side == 'ABOVE') != (name.startswith('above')):
            raise SystemExit('case ' + name + ' landed on the wrong side')
        if raw <= 1e-6 or raw >= 1.0 - 1e-6:
            raise SystemExit('case ' + name + ' saturated; pick another s')
    print('')
    print('=== IOS PROBE GOLDEN DONE ===')


if __name__ == '__main__':
    main()
